name: Terraform Plan

on:
    push:
        branches:
            - main

jobs:
    terraform-plan:
        runs-on: self-hosted
        steps:
  
          - name: Checkout repository
            uses: actions/checkout@v4
          
          - name: Login to Azure
            uses: azure/login@v1
            with:
              creds: ${{ secrets.AZURE_CREDENTIALS }}

          - name: Show current Azure account
            run: az account show
          - name: Set up Terraform
            uses: hashicorp/setup-terraform@v3
            with:
              creds: ${{ secrets.AZURE_CREDENTIALS }}

          - name: Terraform Init
            run: terraform init

          - name: Terraform Validate
            run: terraform validate


          - name: Terraform Plan (Windows Workaround)
            shell: pwsh
            run: |
              terraform init | Write-Output
              terraform plan -out=tfplan | Write-Output
              terraform show -no-color tfplan | Write-Output
           
