name: Terraform Plan

on:
    push:
        branches:
            - main

jobs:
    terraform-plan:
        runs-on: ubuntu-latest
        env:
          TF_VAR_client_id: ${{ secrets.AZURE_CLIENT_ID }}
          TF_VAR_client_secret: ${{ secrets.AZURE_CLIENT_SECRET }}
          TF_VAR_subscription_id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          TF_VAR_tenant_id: ${{ secrets.AZURE_TENANT_ID }}


        steps:
  
          - name: Checkout repository
            uses: actions/checkout@v4

          # - name: Show current Azure account
          #   run: az account show
  
          - name: Set up Terraform
            uses: hashicorp/setup-terraform@v3
            
          - name: Check Terraform Installation
            run: terraform -version

          - name: Terraform Init
            run: terraform init

          - name: Terraform Validate code
            run: terraform validate

          - name: Terraform Plan
            run: TF_LOG=DEBUG terraform plan

          
